#!/usr/bin/env bash
# clickdoc · install.sh
#
# Install clickdoc as a systemd user service on the current machine.
#
# Usage:
#   ./install.sh                       # interactive, sensible defaults
#   ./install.sh --pages /path/pages   # set CLICKDOC_PAGES_DIR
#   ./install.sh --port 9000           # set CLICKDOC_LISTEN_PORT
#   ./install.sh --host 127.0.0.1      # local-only bind
#   ./install.sh --author my-handle    # tag annotations
#   ./install.sh --no-watcher          # don't enable clickdoc.path
#   ./install.sh --uninstall           # remove the service + watcher
#
# What it does:
#   1. Checks Python 3.11+
#   2. Copies clickdoc.service + clickdoc.path to ~/.config/systemd/user/
#      with WorkingDirectory substituted to this clone's actual path
#   3. systemctl --user daemon-reload + enable --now
#   4. Prints the URL to open
#
# No sudo required. Pure user-mode.

set -euo pipefail

REPO_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
UNIT_DIR=${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user
PAGES_DIR=""
STATIC_DIR=""
PORT=8088
HOST=0.0.0.0
AUTHOR=anon
ENABLE_WATCHER=1
UNINSTALL=0

# ---------- arg parse --------------------------------------------------
while [[ $# -gt 0 ]]; do
  case "$1" in
    --pages)        PAGES_DIR="$2"; shift 2 ;;
    --static)       STATIC_DIR="$2"; shift 2 ;;
    --port)         PORT="$2"; shift 2 ;;
    --host)         HOST="$2"; shift 2 ;;
    --author)       AUTHOR="$2"; shift 2 ;;
    --no-watcher)   ENABLE_WATCHER=0; shift ;;
    --uninstall)    UNINSTALL=1; shift ;;
    -h|--help)      sed -n '2,22p' "$0"; exit 0 ;;
    *)              echo "Unknown option: $1" >&2; exit 1 ;;
  esac
done

# ---------- uninstall path ---------------------------------------------
if [[ $UNINSTALL -eq 1 ]]; then
  echo "→ Stopping clickdoc service + watcher"
  systemctl --user disable --now clickdoc.path clickdoc.service 2>/dev/null || true
  rm -f "$UNIT_DIR/clickdoc.service" "$UNIT_DIR/clickdoc.path"
  systemctl --user daemon-reload
  echo "✓ Uninstalled. Annotations DB at ~/.local/share/clickdoc/annotations.db preserved."
  echo "  Delete it manually with: rm -rf ~/.local/share/clickdoc"
  exit 0
fi

# ---------- preflight --------------------------------------------------
echo "→ clickdoc installer"
echo "  repo:       $REPO_DIR"
echo "  unit dir:   $UNIT_DIR"

PY=$(command -v python3 || true)
if [[ -z "$PY" ]]; then
  echo "✗ python3 not found in PATH" >&2; exit 1
fi
PYV=$($PY -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')
PYMIN_OK=$($PY -c 'import sys; print(1 if sys.version_info >= (3,11) else 0)')
if [[ "$PYMIN_OK" != "1" ]]; then
  echo "✗ python $PYV found; clickdoc needs >= 3.11" >&2; exit 1
fi
echo "  python:     $PY ($PYV)"

if ! command -v systemctl >/dev/null; then
  echo "✗ systemctl not found — clickdoc.service requires systemd" >&2
  echo "  You can still run it manually: python3 $REPO_DIR/server.py" >&2
  exit 1
fi

# Test that systemd --user works (no XDG_RUNTIME_DIR = headless box)
if ! systemctl --user list-unit-files >/dev/null 2>&1; then
  echo "✗ 'systemctl --user' does not work (XDG_RUNTIME_DIR unset?)" >&2
  echo "  On headless boxes, run: loginctl enable-linger \$USER" >&2
  exit 1
fi

mkdir -p "$UNIT_DIR"

# ---------- render units -----------------------------------------------
echo "→ Rendering systemd units"
SERVICE_OUT=$UNIT_DIR/clickdoc.service
PATH_OUT=$UNIT_DIR/clickdoc.path

cat > "$SERVICE_OUT" <<EOF
# generated by clickdoc install.sh
[Unit]
Description=clickdoc · live documentation with annotations
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
WorkingDirectory=$REPO_DIR
ExecStart=$PY server.py
Restart=always
RestartSec=3

Environment=CLICKDOC_LISTEN_HOST=$HOST
Environment=CLICKDOC_LISTEN_PORT=$PORT
Environment=CLICKDOC_AUTHOR=$AUTHOR
EOF

if [[ -n "$PAGES_DIR" ]]; then
  PAGES_ABS=$(readlink -f "$PAGES_DIR")
  echo "Environment=CLICKDOC_PAGES_DIR=$PAGES_ABS" >> "$SERVICE_OUT"
  echo "  overlay pages: $PAGES_ABS"
fi
if [[ -n "$STATIC_DIR" ]]; then
  STATIC_ABS=$(readlink -f "$STATIC_DIR")
  echo "Environment=CLICKDOC_STATIC_DIR=$STATIC_ABS" >> "$SERVICE_OUT"
  echo "  overlay static: $STATIC_ABS"
fi

cat >> "$SERVICE_OUT" <<'EOF'

NoNewPrivileges=true
PrivateTmp=true

[Install]
WantedBy=default.target
EOF

# Path watcher
cat > "$PATH_OUT" <<EOF
# generated by clickdoc install.sh
[Unit]
Description=Watch clickdoc pages/static and reload the service

[Path]
PathChanged=$REPO_DIR/pages
PathChanged=$REPO_DIR/static
EOF

if [[ -n "$PAGES_DIR" ]]; then
  echo "PathChanged=$PAGES_ABS" >> "$PATH_OUT"
fi
if [[ -n "$STATIC_DIR" ]]; then
  echo "PathChanged=$STATIC_ABS" >> "$PATH_OUT"
fi

cat >> "$PATH_OUT" <<'EOF'

[Install]
WantedBy=default.target
EOF

# ---------- enable + start ---------------------------------------------
echo "→ Enabling units"
systemctl --user daemon-reload
systemctl --user enable --now clickdoc.service
if [[ $ENABLE_WATCHER -eq 1 ]]; then
  systemctl --user enable --now clickdoc.path
fi

# ---------- smoke test -------------------------------------------------
echo "→ Smoke check"
for i in 1 2 3 4 5; do
  if curl -fsS "http://${HOST/0.0.0.0/127.0.0.1}:$PORT/api/health" >/dev/null 2>&1; then
    echo "✓ clickdoc is running"
    echo
    echo "  Local URL:  http://${HOST/0.0.0.0/127.0.0.1}:$PORT/"
    echo "  Feed:       http://${HOST/0.0.0.0/127.0.0.1}:$PORT/api/feed"
    echo "  Service:    systemctl --user status clickdoc.service"
    echo "  Logs:       journalctl --user -u clickdoc.service -f"
    echo "  Uninstall:  $0 --uninstall"
    exit 0
  fi
  sleep 1
done

echo "✗ Health check failed; inspect: journalctl --user -u clickdoc.service -n 50" >&2
exit 2
